### ISSUE TITLE
project repo renamed to 52

### ISSUE THREAD

**Issue by firasm** [data301-2021-summer2/project-group52-project#1]
Hi @XinDing99 ,

it seems you joined the wrong group on Github. I have renamed your repository to 52, please re-clone this repo locally and manually transfer any files/changes you made since the last time you pushed

**Comment by mkhfring** [comment]
Hello, 

My name is Mohamad, and I will be giving you some feedback on your project. 

Overall, the project is a fantastic start, and  I have some suggestions to improve it.
I have divided up the feedback into several sections, so it is easier for you to implement.

## Task 1

There are some errors in the notebook. Yet, this task is handled. 

## Task 2

Great Work

## Task 3

- Some of your charts don't have any title, description, or legend 

## Task 4

I suggest you have some reports and analyses beside your charts.

**Comment by XinDing99** [comment]
Thanks for your feedback, Mohamad! The updates on charts (title, label, etc) have been updated and put in mileStone 3 jupyter notebook. Besides, the analysis and comments of the charts have been added under each chart.

Thanks!
